# Adapted from https://github.com/JuliaPluto/static-export-template
name: Export Pluto notebooks to GitHub pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pluto-export
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Install Julia
      uses: julia-actions/setup-julia@v2

    - name: Cache Julia depot
      uses: julia-actions/cache@v2

    - name: Set up notebook state cache
      uses: actions/cache@v4
      with:
        path: cache
        key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}-${{ hashFiles('**/*jl') }}
        restore-keys: |
          ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}

    - name: Export Pluto notebooks to HTML
      run: make pkg_instantiate build

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        single-commit: true
